POST http://localhost:3000/order
Content-Type: application/json

{
  "clientName": "Souza",
    "order": "1 x-salada, 1 fanta, 1 batata pequena",
    "price": 27.5,
    "status": "Em preparação"
}


###

GET http://localhost:3000/orders

###

GET http://localhost:3000/order/6d79b32a-c2fe-48ae-82a0-79243d7ff682
###

PUT http://localhost:3000/order/6d79b32a-c2fe-48ae-82a0-79243d7ff682
Content-Type: application/json

{
  "clientName": "Marcelo Souza",
    "order": "1 hotdog, 1 guarana, 1 sorvete",
    "price": 19.9,
    "status": "Em preparação"
}

###

PATCH http://localhost:3000/order/6d79b32a-c2fe-48ae-82a0-79243d7ff682
Content-Type: application/json

{
  "status": "Pronto"
}

###

DELETE http://localhost:3000/order/515c9d2b-b66c-4ac7-9527-887efc9d4543